/**
 * Hardcoded staking contract template.
 *
 * Produces a complete, compilable Solidity contract that can be used as a
 * template-based fallback when no Anthropic API key is configured.
 */

export interface StakingContractParams {
  name: string;
  rewardRateBps: number;
  lockDurationSec: number;
  maxTotalStaked: string | undefined;
  hasEmergencyWithdraw: boolean;
  hasCompounding: boolean;
}

export function generateStakingContract(params: StakingContractParams): string {
  const {
    name,
    rewardRateBps,
    lockDurationSec,
    maxTotalStaked,
    hasEmergencyWithdraw,
    hasCompounding,
  } = params;

  const maxStakedParam = maxTotalStaked ? ", uint256 maxStaked_" : "";
  const maxStakedInit = maxTotalStaked ? "\n        $.maxStaked = maxStaked_;" : "";
  const maxStakedCheck = maxTotalStaked
    ? `
        if ($.maxStaked > 0) {
            require($.totalStaked + amount <= $.maxStaked, "Max total staked exceeded");
        }`
    : "";

  const emergencyWithdrawFn = hasEmergencyWithdraw
    ? `
    /// @notice Emergency withdraw all staked tokens, forfeiting pending rewards.
    /// @dev Bypasses lock period. Only available when contract is paused.
    function emergencyWithdraw() external nonReentrant whenPaused {
        StakingStorage storage $ = _getStakingStorage();
        StakerInfo storage staker = $.stakers[msg.sender];

        uint256 amount = staker.amount;
        require(amount > 0, "Nothing staked");

        $.totalStaked -= amount;
        staker.amount = 0;
        staker.rewardDebt = 0;
        staker.lockUntil = 0;

        $.stakeToken.safeTransfer(msg.sender, amount);

        emit EmergencyWithdrawn(msg.sender, amount);
    }`
    : "";

  const emergencyWithdrawEvent = hasEmergencyWithdraw
    ? "\n    event EmergencyWithdrawn(address indexed user, uint256 amount);"
    : "";

  const compoundFn = hasCompounding
    ? `
    /// @notice Compound pending rewards by re-staking them.
    /// @dev Requires that the reward token is the same as the stake token.
    function compoundRewards() external nonReentrant whenNotPaused {
        StakingStorage storage $ = _getStakingStorage();

        _updatePool();

        StakerInfo storage staker = $.stakers[msg.sender];
        uint256 pending = (staker.amount * $.accRewardPerShare / PRECISION) - staker.rewardDebt;
        require(pending > 0, "No rewards to compound");

        staker.amount += pending;
        $.totalStaked += pending;
        staker.rewardDebt = staker.amount * $.accRewardPerShare / PRECISION;

        emit Compounded(msg.sender, pending);
    }`
    : "";

  const compoundEvent = hasCompounding
    ? "\n    event Compounded(address indexed user, uint256 amount);"
    : "";

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ZappBaseUpgradeable} from "../ZappBaseUpgradeable.sol";

/// @title ${name}
/// @notice Staking contract with MasterChef-style reward-per-share accumulator.
/// @dev Generated by the Zapp dApp builder. Inherits ZappBaseUpgradeable which
///      provides UUPS upgradeability, AccessControl, ReentrancyGuard, and Pausable.
///      Uses ERC-7201 namespaced storage.
contract ${name} is ZappBaseUpgradeable {
    using SafeERC20 for IERC20;

    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    /// @dev Precision multiplier for reward-per-share math (1e18).
    uint256 private constant PRECISION = 1e18;

    /// @dev Basis-points denominator (10_000 = 100%).
    uint256 private constant BPS_DENOMINATOR = 10_000;

    /// @dev Seconds in one year (365 days) for annualized reward calculation.
    uint256 private constant SECONDS_PER_YEAR = 365 days;

    // -----------------------------------------------------------------------
    // ERC-7201 Namespaced Storage
    // -----------------------------------------------------------------------

    /// @dev Staker accounting information.
    struct StakerInfo {
        uint256 amount;
        uint256 rewardDebt;
        uint256 stakedAt;
        uint256 lockUntil;
    }

    /// @custom:storage-location erc7201:zapp.storage.staking
    struct StakingStorage {
        IERC20 stakeToken;
        uint256 rewardRateBps;
        uint256 lockDuration;
        uint256 totalStaked;
        uint256 accRewardPerShare;
        uint256 lastRewardTimestamp;
        uint256 maxStaked;
        mapping(address => StakerInfo) stakers;
    }

    // keccak256(abi.encode(uint256(keccak256("zapp.storage.staking")) - 1)) & ~bytes32(uint256(0xff))
    bytes32 private constant STAKING_STORAGE_LOCATION =
        0xe4ddc35a5c6cfac23313c698823eea3b4637a1b49ee4e0e1fded9f4b85415000;

    function _getStakingStorage() private pure returns (StakingStorage storage $) {
        assembly {
            $.slot := STAKING_STORAGE_LOCATION
        }
    }

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------

    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event RewardsClaimed(address indexed user, uint256 amount);
    event RewardRateUpdated(uint256 oldRate, uint256 newRate);${compoundEvent}${emergencyWithdrawEvent}

    // -----------------------------------------------------------------------
    // Initializer
    // -----------------------------------------------------------------------

    /// @notice Initializes the staking contract.
    /// @param dappId_      Unique dApp identifier.
    /// @param admin_       Address that receives DEFAULT_ADMIN_ROLE.
    /// @param upgrader_    Address that receives UPGRADER_ROLE.
    /// @param stakeToken_  ERC-20 token used for staking and rewards.
    /// @param rewardRateBps_ Annual reward rate in basis points (500 = 5%).
    /// @param lockDuration_ Minimum lock period in seconds (0 = no lock).
    function initialize(
        string memory dappId_,
        address admin_,
        address upgrader_,
        address stakeToken_,
        uint256 rewardRateBps_,
        uint256 lockDuration_${maxStakedParam}
    ) external initializer {
        __ZappBase_init(dappId_, admin_, upgrader_);

        require(stakeToken_ != address(0), "Invalid token address");
        require(rewardRateBps_ <= BPS_DENOMINATOR, "Rate exceeds 100%");

        StakingStorage storage $ = _getStakingStorage();
        $.stakeToken = IERC20(stakeToken_);
        $.rewardRateBps = rewardRateBps_;
        $.lockDuration = lockDuration_;
        $.lastRewardTimestamp = block.timestamp;${maxStakedInit}
    }

    // -----------------------------------------------------------------------
    // User Functions
    // -----------------------------------------------------------------------

    /// @notice Stake tokens into the pool.
    /// @param amount The amount of tokens to stake (must be > 0).
    function stake(uint256 amount) external nonReentrant whenNotPaused {
        require(amount > 0, "Cannot stake 0");

        StakingStorage storage $ = _getStakingStorage();${maxStakedCheck}

        _updatePool();

        StakerInfo storage staker = $.stakers[msg.sender];

        // If the staker already has tokens, harvest pending rewards first
        if (staker.amount > 0) {
            uint256 pending = (staker.amount * $.accRewardPerShare / PRECISION) - staker.rewardDebt;
            if (pending > 0) {
                $.stakeToken.safeTransfer(msg.sender, pending);
                emit RewardsClaimed(msg.sender, pending);
            }
        }

        $.stakeToken.safeTransferFrom(msg.sender, address(this), amount);

        staker.amount += amount;
        staker.stakedAt = block.timestamp;
        staker.lockUntil = block.timestamp + $.lockDuration;
        staker.rewardDebt = staker.amount * $.accRewardPerShare / PRECISION;
        $.totalStaked += amount;

        emit Staked(msg.sender, amount);
    }

    /// @notice Unstake tokens from the pool and claim pending rewards.
    /// @param amount The amount of tokens to unstake (must be > 0 and <= staked amount).
    function unstake(uint256 amount) external nonReentrant whenNotPaused {
        require(amount > 0, "Cannot unstake 0");

        StakingStorage storage $ = _getStakingStorage();
        StakerInfo storage staker = $.stakers[msg.sender];

        require(staker.amount >= amount, "Insufficient staked balance");
        require(block.timestamp >= staker.lockUntil, "Tokens still locked");

        _updatePool();

        // Harvest pending rewards
        uint256 pending = (staker.amount * $.accRewardPerShare / PRECISION) - staker.rewardDebt;
        if (pending > 0) {
            $.stakeToken.safeTransfer(msg.sender, pending);
            emit RewardsClaimed(msg.sender, pending);
        }

        staker.amount -= amount;
        staker.rewardDebt = staker.amount * $.accRewardPerShare / PRECISION;
        $.totalStaked -= amount;

        $.stakeToken.safeTransfer(msg.sender, amount);

        emit Unstaked(msg.sender, amount);
    }

    /// @notice Claim accumulated rewards without unstaking.
    function claimRewards() external nonReentrant whenNotPaused {
        StakingStorage storage $ = _getStakingStorage();
        StakerInfo storage staker = $.stakers[msg.sender];

        _updatePool();

        uint256 pending = (staker.amount * $.accRewardPerShare / PRECISION) - staker.rewardDebt;
        require(pending > 0, "No rewards to claim");

        staker.rewardDebt = staker.amount * $.accRewardPerShare / PRECISION;

        $.stakeToken.safeTransfer(msg.sender, pending);

        emit RewardsClaimed(msg.sender, pending);
    }
${compoundFn}${emergencyWithdrawFn}

    // -----------------------------------------------------------------------
    // View Functions
    // -----------------------------------------------------------------------

    /// @notice Returns the pending (unclaimed) reward for a user.
    /// @param user The address to query.
    /// @return The pending reward amount.
    function pendingRewards(address user) external view returns (uint256) {
        StakingStorage storage $ = _getStakingStorage();
        StakerInfo storage staker = $.stakers[user];

        uint256 accReward = $.accRewardPerShare;

        if (block.timestamp > $.lastRewardTimestamp && $.totalStaked > 0) {
            uint256 elapsed = block.timestamp - $.lastRewardTimestamp;
            uint256 reward = ($.totalStaked * $.rewardRateBps * elapsed) / (BPS_DENOMINATOR * SECONDS_PER_YEAR);
            accReward += (reward * PRECISION) / $.totalStaked;
        }

        return (staker.amount * accReward / PRECISION) - staker.rewardDebt;
    }

    /// @notice Returns staker info for a given address.
    /// @param user The address to query.
    /// @return amount The staked amount.
    /// @return rewardDebt The reward debt used in accumulator math.
    /// @return stakedAt Timestamp of last stake.
    /// @return lockUntil Timestamp when tokens can be unstaked.
    function getStakerInfo(address user)
        external
        view
        returns (uint256 amount, uint256 rewardDebt, uint256 stakedAt, uint256 lockUntil)
    {
        StakingStorage storage $ = _getStakingStorage();
        StakerInfo storage staker = $.stakers[user];
        return (staker.amount, staker.rewardDebt, staker.stakedAt, staker.lockUntil);
    }

    /// @notice Returns global pool statistics.
    /// @return totalStaked_ Total tokens staked in the pool.
    /// @return rewardRateBps_ Annual reward rate in basis points.
    /// @return lockDuration_ Minimum lock period in seconds.
    /// @return accRewardPerShare_ Current reward accumulator value.
    function getPoolInfo()
        external
        view
        returns (uint256 totalStaked_, uint256 rewardRateBps_, uint256 lockDuration_, uint256 accRewardPerShare_)
    {
        StakingStorage storage $ = _getStakingStorage();
        return ($.totalStaked, $.rewardRateBps, $.lockDuration, $.accRewardPerShare);
    }

    // -----------------------------------------------------------------------
    // Admin Functions
    // -----------------------------------------------------------------------

    /// @notice Update the annual reward rate.
    /// @param newRateBps New rate in basis points (max 10000 = 100%).
    function setRewardRate(uint256 newRateBps) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(newRateBps <= BPS_DENOMINATOR, "Rate exceeds 100%");

        _updatePool();

        StakingStorage storage $ = _getStakingStorage();
        uint256 oldRate = $.rewardRateBps;
        $.rewardRateBps = newRateBps;

        emit RewardRateUpdated(oldRate, newRateBps);
    }

    // -----------------------------------------------------------------------
    // Internal
    // -----------------------------------------------------------------------

    /// @dev Updates the global reward accumulator based on elapsed time.
    function _updatePool() internal {
        StakingStorage storage $ = _getStakingStorage();

        if (block.timestamp <= $.lastRewardTimestamp) {
            return;
        }

        if ($.totalStaked == 0) {
            $.lastRewardTimestamp = block.timestamp;
            return;
        }

        uint256 elapsed = block.timestamp - $.lastRewardTimestamp;
        uint256 reward = ($.totalStaked * $.rewardRateBps * elapsed) / (BPS_DENOMINATOR * SECONDS_PER_YEAR);

        $.accRewardPerShare += (reward * PRECISION) / $.totalStaked;
        $.lastRewardTimestamp = block.timestamp;
    }

    /// @notice Public entry point to update the reward accumulator.
    function updatePool() external {
        _updatePool();
    }
}
`;
}
