// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Initializable} from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import {UUPSUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import {AccessControlUpgradeable} from "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {PausableUpgradeable} from "@openzeppelin/contracts-upgradeable/utils/PausableUpgradeable.sol";

/// @title ZappBaseUpgradeable
/// @notice Base contract for all dApps generated by the Zapp platform.
/// @dev Inherits UUPS proxy, AccessControl, ReentrancyGuard, and Pausable.
///      All generated contracts should inherit from this and call __ZappBase_init
///      in their initializer.
abstract contract ZappBaseUpgradeable is
    Initializable,
    UUPSUpgradeable,
    AccessControlUpgradeable,
    ReentrancyGuard,
    PausableUpgradeable
{
    bytes32 public constant UPGRADER_ROLE = keccak256("UPGRADER_ROLE");

    /// @custom:storage-location erc7201:zapp.storage.Base
    struct BaseStorage {
        string dappId;
        uint256 version;
    }

    // keccak256(abi.encode(uint256(keccak256("zapp.storage.Base")) - 1)) & ~bytes32(uint256(0xff))
    bytes32 private constant BASE_STORAGE_LOCATION =
        0xefb850fee152e803ca1e7708b20a0c69944757e2d8f1391ce995eb1f17fb2400;

    function _getBaseStorage() private pure returns (BaseStorage storage $) {
        assembly {
            $.slot := BASE_STORAGE_LOCATION
        }
    }

    /// @notice Initializes the base Zapp contract.
    /// @param dappId_ Unique identifier for the dApp instance.
    /// @param admin_ Address that receives DEFAULT_ADMIN_ROLE.
    /// @param upgrader_ Address that receives UPGRADER_ROLE.
    function __ZappBase_init(
        string memory dappId_,
        address admin_,
        address upgrader_
    ) internal onlyInitializing {
        __AccessControl_init();
        // ReentrancyGuard uses transient storage in OZ 5.x — no init needed
        __Pausable_init();

        _grantRole(DEFAULT_ADMIN_ROLE, admin_);
        _grantRole(UPGRADER_ROLE, upgrader_);

        BaseStorage storage $ = _getBaseStorage();
        $.dappId = dappId_;
        $.version = 1;
    }

    /// @notice Returns the dApp identifier set at initialization.
    function dappId() public view returns (string memory) {
        return _getBaseStorage().dappId;
    }

    /// @notice Returns the current implementation version (incremented on each upgrade).
    function contractVersion() public view returns (uint256) {
        return _getBaseStorage().version;
    }

    /// @notice Pauses the contract. Only callable by DEFAULT_ADMIN_ROLE.
    function pause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        _pause();
    }

    /// @notice Unpauses the contract. Only callable by DEFAULT_ADMIN_ROLE.
    function unpause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        _unpause();
    }

    /// @dev Restricts upgrades to UPGRADER_ROLE and increments the version counter.
    function _authorizeUpgrade(
        address newImplementation
    ) internal override onlyRole(UPGRADER_ROLE) {
        _getBaseStorage().version += 1;
    }
}
